url: 'https://blog.voterheads.com'
baseurl: ''
title: 'Voterheads Blog'

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - node_modules
  - src
